"""Generate native-WebCrypto chunk digests only from the verified USA 1.02 ISO."""
import argparse
import hashlib
import json
from pathlib import Path

ISO_SHA256 = '0de05981a34156b9cedcef73c73d4244ac05cf6149ab3c9cfed917698819e464'
ISO_SIZE = 1459978240
CHUNK_BYTES = 64 * 1024 * 1024


def generate(path):
    whole = hashlib.sha256()
    chunks = []
    size = 0
    with path.open('rb') as stream:
        while block := stream.read(CHUNK_BYTES):
            whole.update(block)
            size += len(block)
            chunks.append(hashlib.sha256(block).hexdigest())
    if size != ISO_SIZE or whole.hexdigest() != ISO_SHA256:
        raise ValueError('Expected the full, unmodified USA 1.02 Melee ISO')
    return dict(size=size, chunkBytes=CHUNK_BYTES, isoSha256=ISO_SHA256, chunks=chunks)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('iso', type=Path)
    args = parser.parse_args()
    manifest = generate(args.iso)
    output = Path(__file__).resolve().parents[1] / 'runtime/web/disc-chunks.mjs'
    output.write_text('// Generated by tools/build_disc_verification.py from the verified USA 1.02 disc.\n'
                      '// Digests only; no game data. Every byte is checked, including disc padding.\n'
                      'export default ' + json.dumps(manifest, indent=2) + ';\n')
